owner: tilde-cornell
repo: CornellTildeUptime

sites:
  - name: tilde@Cornell Site
    url: https://cornelltilde.com/
    type: globalping
  - name: tilde@Cornell Email UI
    url: https://mail.cornelltilde.com
    type: globalping
  - name: tilde@Cornell SMTPS
    url: mail.cornelltilde.com
    port: 465
    check: "tcp-ping"
    type: globalping
  - name: tilde@Cornell STARTTLS
    url: mail.cornelltilde.com
    port: 587
    check: "tcp-ping"
    type: globalping
  - name: tilde@Cornell IMAPS
    url: mail.cornelltilde.com
    port: 993
    check: "tcp-ping"
    type: globalping
  - name: tilde@Cornell Forgejo
    url: https://code.cornelltilde.com
    type: globalping
  - name: tilde@Cornell Forgejo SSH
    url: code.cornelltilde.com
    port: 2222
    check: "tcp-ping"
    type: globalping
  - name: tilde@Cornell SSO service
    url: https://sso.cornelltilde.com
    type: globalping
  - name: tilde@Cornell Dev Server
    url: https://dev.cornelltilde.com
    type: globalping

status-website:
  cname: status.cornelltilde.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: tilde@Cornell Uptime
  introTitle: tilde@Cornell Uptime
  #introMessage: Generic Intro Message - Don't think we need this
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

runner: "[self-hosted, linux, ARM64]"
