owner: Eason-Y-Lu
repo: CornellTildeUptime

sites:
  - name: tilde@Cornell
    url: https://cornelltilde.com/
  - name: tilde@Cornell SMTP
    url: mail.cornelltide.com
    port: 465, 587, 993
    check: "tcp-ping"
    #- name: IPv6 test
    # url: forwardemail.net
    # port: 80
    # check: "tcp-ping"
    # ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cornelltilde.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: tilde@Cornell Uptime
  introTitle: Generic Intro Title
  introMessage: Generic Intro Message
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
